# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - stefrensma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present # Only build here

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for test and deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  test: # This job will run tests on the built artifact
    runs-on: ubuntu-latest
    needs: build # Depends on the build job completing successfully
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for tests
        run: unzip release.zip

      - name: Set up Node.js (needed to run npm commands)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match your build job's Node.js version

      - name: Install dependencies (if not included in artifact, or if tests have their own dependencies)
        run: npm install

      - name: Wait for database to be ready (replace with your actual check)
        run: |
          mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SELECT 1"

      - name: Run tests
        run: npm test
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E18B97F2D1934F159BCBB59F6260F792 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B738650E920C4CB3995CD1B1547B3A40 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D40AC7836762462F8CEC686C9EBE4812 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'stefrensma'
          slot-name: 'Production'
          package: .